import { betterAuth } from "better-auth";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { Pool, neonConfig } from "@neondatabase/serverless";
import { drizzle } from "drizzle-orm/neon-serverless";
import * as schema from "./db/schema";
import ws from "ws";

// Configure Neon to use WebSocket for reliable connections
// This fixes ETIMEDOUT and ENETUNREACH errors in WSL2/serverless environments
neonConfig.webSocketConstructor = ws;

// Validate DATABASE_URL is configured
if (!process.env.DATABASE_URL) {
  throw new Error(
    "DATABASE_URL environment variable is required for Better Auth. " +
    "Check your .env.local file and ensure it contains a valid Neon PostgreSQL connection string."
  );
}

// Validate DATABASE_URL format for Neon
if (!process.env.DATABASE_URL.includes("sslmode=require")) {
  console.warn(
    "⚠️  DATABASE_URL should include '?sslmode=require' for Neon PostgreSQL. " +
    "Connection may fail without SSL mode."
  );
}

// Create Neon WebSocket Pool with retry-friendly configuration
// WebSocket driver is MORE RELIABLE than HTTP driver for:
// - WSL2 environments (avoids IPv6 issues)
// - Serverless cold starts
// - Connection persistence
const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  // Connection pool settings optimized for serverless
  max: 10,                    // Maximum connections in pool
  idleTimeoutMillis: 30000,   // Close idle connections after 30s
  connectionTimeoutMillis: 10000, // Wait up to 10s for connection
});

// Handle pool errors gracefully (prevents unhandled rejections)
pool.on("error", (err: Error) => {
  console.error("Neon Pool error:", err.message);
});

const db = drizzle(pool, { schema });

// Determine if we're in production
// CRITICAL: NODE_ENV must be checked correctly for cookie settings
const isProduction = process.env.NODE_ENV === "production";

// Log environment for debugging cookie issues
if (typeof window === "undefined") {
  console.log("[Better Auth] Server Config:", {
    NODE_ENV: process.env.NODE_ENV,
    isProduction,
    baseURL: process.env.BETTER_AUTH_URL || "http://localhost:3000",
    secureCookies: isProduction,
  });
}

/**
 * Better Auth server configuration.
 *
 * IMPORTANT: JWT tokens for the backend API are handled by a SEPARATE
 * custom endpoint at /api/auth/token (see frontend/src/app/api/auth/token/route.ts).
 *
 * This configuration handles:
 * - Email/password authentication
 * - Session management in PostgreSQL (cookies)
 *
 * COOKIE FIX: Session cookies were not persisting because:
 * 1. useSecureCookies must be FALSE for HTTP localhost (secure cookies ONLY work on HTTPS)
 * 2. sameSite must be 'lax' for proper same-site navigation
 * 3. Cross-site cookie settings were preventing cookie storage
 */
export const auth = betterAuth({
  secret: process.env.BETTER_AUTH_SECRET!,
  baseURL: process.env.BETTER_AUTH_URL || "http://localhost:3000",

  // Trusted origins for CSRF protection
  // CRITICAL: Must include all origins that will make requests
  trustedOrigins: [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    process.env.BETTER_AUTH_URL || "http://localhost:3000",
    "https://my-todo-app-mu-hazel.vercel.app", // Production
    "https://my-todo-recuuopsq-amna-ejaz16s-projects.vercel.app", // Preview
  ],

  // Database configuration using Drizzle adapter with Neon WebSocket
  database: drizzleAdapter(db, {
    provider: "pg",
    schema: schema,
  }),

  // Email and password authentication
  emailAndPassword: {
    enabled: true,
    minPasswordLength: 8,
  },

  // Session configuration
  session: {
    expiresIn: 60 * 60 * 24 * 7, // 7 days
    updateAge: 60 * 60, // Update session every hour if active
    // DISABLED cookie cache - it can cause issues with session detection
    // The session_token cookie alone is sufficient and more reliable
    cookieCache: {
      enabled: false,
    },
  },

  // Cookie and security configuration
  // CRITICAL FIX: These settings control cookie persistence
  advanced: {
    // Cookie name prefix
    cookiePrefix: "better-auth",

    // CRITICAL: Must be FALSE for localhost HTTP development
    // Secure cookies are ONLY sent over HTTPS connections
    // If this is true on localhost:3000 (HTTP), cookies will NOT be set
    useSecureCookies: isProduction,

    // Disable CSRF check in development for easier testing
    disableCSRFCheck: !isProduction,

    // Default cookie sameSite setting
    // 'lax' allows cookies on same-site navigations (clicking links, form submissions)
    // This is essential for the signin → dashboard redirect flow
    defaultCookieAttributes: {
      sameSite: "lax",
      path: "/",
    },
  },

  // NO JWT plugin - tokens are generated by custom /api/auth/token endpoint
  // This avoids the JWKS initialization errors while maintaining HS256 compatibility
});

export type Session = typeof auth.$Infer.Session;
